shared:
  appID: &appID 18238
botConfig:
  appID: *appID
  termList:
    - master
    - slave
    - whitelist
    - blacklist
  checkName: Inclusive Language Check
  checkSuccessSummary: Looks good! ðŸ˜‡
  checkFailureSummary: ðŸ‘‹ exclusive language
  checkDetails: Found exclusive language
  annotationTitle: Exclusive Language
  annotationBody: |
    Hi there! ðŸ‘‹ I see you used the term(s) [%s] here. This language is exclusionary for members of our community,
    please consider changing it. For more info, see the [wiki page](https://zendesk.atlassian.net/wiki/spaces/ENG/pages/631834099/Engineering+Inclusion)
clientConfig:
  appID: *appID
  privateKeyPath: /secrets/PRIVATE_KEY
